### ISSUE TITLE
Feed move problem

### ISSUE THREAD

**Issue by DBSDBS** [grbl/grbl#1076]
Hi,

I use the last version of GRBL for a Laser engraver.
The setup is:
Arduino Uno
CNC shield
DRV8825 drivers set for 16 microsteps
Laser driver connected to Z max

When the code is with G0 the movement is smooth
But when I send G1 codes, the machine makes little "stops" on every node the curve is made from.
This is a big problem, because the the movement decelerates + stops (for let say 0.2 s) + accelerates. In the same moment, the power of the laser stays the same, and as a result, I receive the same "wire with nodes" as in the vector program. In my case I use Vectric Aspire with [THIS Post Processor](https://jtechphotonics.com/?p=3851).

Can someone help me with an advise what is wrong with my setup?

Thank you in advance.

Best Regards

Denis

**Comment by chamnit** [comment]
@DBSDBS : Grbl v0.9 is not setup for laser engraving at this time. v1.0 will be. The main issue is Grbl assumes it'll be used by a CNC with a spindle-like tool, where you want to stop and let the spindle get up to rpm before continuing. With a laser, you want continuous motion, since the laser can adjust power instantly. There are some Grbl variants that has a laser engraving mode, so I suggest trying those until v1.0 is released.
