### ISSUE TITLE
Feed rate fractional numerals ?

### ISSUE THREAD

**Issue by 71Slava** [grbl/grbl#1079]
Please tell me how to make the feed rate of less than 1 mm / min? (For example 0.5 mm / min)

**Comment by jahnj0584** [comment]
When would this ever be needed?

**Comment by chamnit** [comment]
@71Slava : You'll need to alter the config.h file. It is set for a minimum of 1.0 mm/min. Depending on how slow you are going and what your steps/mm are, you may need to disable AMASS because it has a hard limit on how many steps it can pulse per second. Disabling it allows you to move as slow as you want.

**Comment by 71Slava** [comment]
Thank you! I'll try. I experiment with continuous 3D printing sla dlp clip.
For different photopolymers required precisely to expose speed of movement z axis.
