### ISSUE TITLE
Grbl on Arduino Leonardo?

### ISSUE THREAD

**Issue by chamnit** [grbl/grbl#111]
Just noticed that the Arduino Leonardo has been released. So, I'd like to start a discussion on what changes this would entail for Grbl. The main difference is that the Leonardo is based on a Atmega32U4 chip, rather than the Atmega328p with a AtmegaXU2 or FTDI USB-to-serial chip. Here's a short list of the differences between the two.
- More SRAM memory 2.5K from 2K. This could mean up to 20-25 acceleration planner blocks from 16-18 now. Or larger receive streaming buffers, etc. What's the best way to use the increase in memory?
- (Possibly) 4 more digital I/O pins. Apparently these maybe inaccessible, since they have been mapped to the ICSP header and another terminated. Haven't played with one, but would like to know if this could be easily hijacked for use. Maybe for 4th axis?
- More Timers! If I understand this correctly, instead of two 8-bit and one 16-bit timers, the Leonardo has one 8-bit, two 16-bit, and a 10-bit high speed timer on-board. Not exactly sure what this would mean for Grbl. Open to some ideas here.
- Full-speed USB / No serial chip. This means that the main processor is now handling all communications. I imagine that Grbl will need to include a lot of these drivers into its code-base to support this, but I could be wrong. This also means that the basic serial interface that Grbl uses may be obsolete. One thing for sure is that this could throw a wrench into things on how Grbl communicates and GUIs interact.
- Separation of serial and USB comm: This means that the digital I/O pins are no longer tied to D0 and D1 and is instead performed through virtualization software unless explicitly compiled-in. Which means there may be an additional two digital I/O pins that can be used for a 4-axis or something else.
- Reset oddities: When connecting through the serial interface, a sketch is not automatically reset as in previous Arduinos, instead the program continues to run. Also, upon a hard reset of the Leonardo, the device completely disconnects from the host computer and connect must be re-established. Not sure how this will affect 3rd party GUIs but some thought and testing will likely need to be done to see how this works exactly,.

**Comment by unorthodox-engineers** [comment]
Hey, everyone. I really wish I'd found this thread a while ago...

I've been porting grbl0.9j to the Leonardo/32u4 over the last week, mostly because I didn't realize it had already been tried... (yes, I did search, but apparently not hard enough.) And in many ways the port is actually done and working... I can control it with "Grbl Controller" just fine and get moving axis feedback. And I haven't had to drop any features, just turn GUI_REPORTING on. (0.9j has AMASS, Spindle PWM and other improvements) Yes, I remapped Timer2 -> Timer4, and I've been using the Teensy USB lib and stock bootloader. (no LUFA)

However, while doing the 'clean up' of assigning ports and pins and timers, I ran into the (well known here, apparently) problem with the USB interrupt vectors being higher priority than the Timer interrupts. I was wondering if anyone had come up with a solution to that, or tried any of the following:

1. Poll-driven USB driver - who knows, there might be a rewrite of the USB/CDC routines to be polling rather than interrupt driven. That could also be a pit of despair from which no soul returns.

2. Re-enable interrupts early in USB vector - don't know if this one works on atmegas, but on most processors you can re-enable the global interrupt while masking out the current interrupt (to prevent re-entrance) and then re-enable the local interrupt at the end. That way lower priority interrupts still happen with slight latency.

3. Hardware Interrupt Escalation - If a timer output signal was routed to the INT0 pin, then it would be able to interrupt the USB vector. In fact, OC0B comes out on that pin. Perhaps we can use one (unconnected) pin to 'escalate' the interrupt to INT0 - assuming we can make it an output while simultaneously being 'input' enough to cause hardware interrupts. Worst case, two pins need to be jumpered to connect a timer output like OC4A to INT0. There might be extra cycles of latency, though, and weird co-timing issues.

4. Ignore It. - If the USB interrupt routine is fast enough, then the jitter will be minimal on slow systems - and perhaps driving steppers won't be the purpose of the device. (just spindle/coolant control or similar.)

I'll take a look through the "rdpowers/grbl" repo in case there's something useful in there, but any suggestions would be great. I'm sooo close.

**Comment by pistolero** [comment]
@unorthodox-engineers so, did you managed to solve interrupt priority issue? Can you share your modifications?

**Comment by unorthodox-engineers** [comment]
Yup. The problems turned out to be non-existant... the USB interrupts all occur during the setup/handshaking stage, and once the endpoints are established everything is handled by the u32's hardware FIFO buffers and polled calls. It's actually quite neat in there. I can confirm that the Leonardo is perfectly capable of running grbl glitch-free at quite high speeds.

In fact, the USB link is technically superior to the serial link or USB converter on the UNO... due to the hardware-level checksum / retransmission / flow control. (The equivalent of XON/XOFF is built in) You can get right up into the stack, on the 32u4, and do all kinds of fun things.

There was a lot of messing around with the Timer and GPIO pins though... pretty much everything got reassigned, making GrblShields useless which I wasn't happy with, and I'm still looking to ameliorate.

There's also an issue with USB "HIDS" (Hardware ID's) which turned out to be a rabbit hole of astonishing proportions. Basically, The "USB Implementers Forum" (The USB equivalent of the MPAA) collects licencing fees for handing out hardware IDs. Unsurprisingly, there are no "class IDs" for generic serial ports. Every USB device manufacturer is supposed to drop $4k on getting a HID, and allowing other people to use your HID is legal grounds for having your keys revoked.

Technically, the HIDs on your Arduino are only licenced for the Arduino LLC firmware. To do things properly, we should get an "Official" grbl HID from OpenMoko (who, due to a licencing glitch, has one of the few re-assignable HID blocks that exists, and gives out ID's to open source projects.) and then write a Windows .inf driver that uses that ID. (Yes, really. This is why every damn serial port device seems to have it's own driver files and the Cypress chip is so popular. The makers have little choice. Just feel glad that Microsoft/Linux/Apple ignored the spec and don't require one for each individual USB Flash drive / mouse / webcam.)

If we got a HID and compiled in unique/random product serial IDs, then grbl devices could be explicitly identified as such by the OS. They'd always get assigned the same COM port. And you could even add linux udev entries that detect the connection and run programs. I think that's a level of reliability that might be worth the trouble, but it's still an effort.

I've been in (extensive!) communication with Sungeun and he's got big chunks of the code I developed, especially the USB driver, but because I made so many other changes as well (replaced stepper output with DAC code for galvos, etc) it's a little difficult to just drag those changes in without at least one of us having access to both platforms. He's only got Unos, and I've only got Leonardos, and that raises the difficulty level to 'hard'. Also, I broke my laser, so I can't test at all right now :-( 

It's tempting to just branch and publish, but that's probably a great way to cause a fork, and we've got enough of those already.

If you have a desperate need, let me know and I'll send you the code I have. It will need changes for your platform (especially if you're using steppers again) and you might need to debug a few features like limit switches. I won't be getting back to this until after Christmas at least.

What we really need is someone who has a good testing setup with both platforms, and can verify our builds. Then Sungeun and I can hack on the code, and get told when we've broken the other branch.

**Comment by cri-s** [comment]
You surely don't want having own HID/VID for open source project.
The driver needs signed, that is yearly fee, for Micro$oft at least.
Even on apple needs to
be signed, but because it's very old requirement, it is possible that is free.
And running Win7-8 without sign necessary is possible for nerd, not
really for real users,
but win10 don't allow that anymore.
You can use  VID decimal 5824 (hexadecimal 0x16C0) and range VID
decimal 1000-1009
for testing with this restrictions:
the gadgets in which you use those PIDs do not leave your desk, and
you won't complain to me if you get in trouble with duplicate PIDs
(for instance because someone else did not follow the previous rule).


2015-11-28 1:43 GMT, Jeremy Lee <notifications@github.com>:

**Comment by mimsou** [comment]
Hi everyone '
Let me say that you all are achived a great job ,  i uploaded the 0.8 c grbl version in my leonardo and until now it works for me 

I was asking if the 0.9 vertion for the 32u4 is availble as well i want to do pcb probing but it apear that s Impossible with the 0.8c thx for your help 

My email souheyeb@gmail.com

**Comment by BernardG** [comment]
Just saw this today: http://www.arduino.org/products/boards/arduino-industrial-101 along with this paper: http://www.rs-online.com/designspark/electronics/eng/blog/getting-arduino-industrial-101, and I wondered if this could make you, @chamnit, reconsider an official port to the 32u4?

Looks like this board would allow relatively easily yo have both GRBL and the GRBL controller on the same board (or a website), maybe allowing to do a few things with the GCode outside of GRBL, like controlling spindle RPM.

**Comment by chamnit** [comment]
@BernardG : No. Not at the moment. After v1.0 is released, I'll be more open to accepting pull requests, which up to this point, I haven't at all due to the 328p's constraints. IMHO, 328 (and the 32U4) are nearing the end of its capability. I'm not sure it's worth the effort to support the 32U4, when I'll personally be ceasing development on the 328p version of Grbl after v1.0 and investing all of my time in the ARM version.

**Comment by BernardG** [comment]
Thanks for your answer, it make sense. Great to know there is a future on ARM for GRBL.
