### ISSUE TITLE
need to always enable motors

### ISSUE THREAD

**Issue by vladislav-konoplyev** [grbl/grbl#1139]
Hello! I need to use grbl in wall plotter project. In this case i need that drivers should be always enable. When i do DEFAULT_STEPPER_IDLE_LOCK_TIME = 255 in defaults_generic.h , nothing changes.
How should i solve this problem, tell me please?
Best regards

**Comment by chamnit** [comment]
@vladislav-konoplyev : You need to either write that value in manually with a $ command or restore your EEPROM with a `$RST=*`, which will wipe everything and reload all defaults.

**Comment by vladislav-konoplyev** [comment]
Thanks a lot!

**Comment by vladislav-konoplyev** [comment]
i try to send $RST=* and try to clean EEPROM than recompile grbl and upload, but nothing help.
grbl answer after $RST=* - "restore defaults ok" but nothing changes in behavior of plotter. drivers doesn't always enable. What i do wrong?
Best regards

**Comment by jahnj0584** [comment]
If you changed the grbl code you have to load it into the Arduino IDE with
a different name. Otherwise it'll ignore it if there's already the same
name in the library.
You can also just do $1=255 in your control software

On Dec 3, 2016 9:33 AM, "Uladzislau Kanapliou" <notifications@github.com>
wrote:

i try to send $RST=* and try to clean EEPROM than recompile grbl and
upload, but nothing help.
grbl answer after $RST=* - "restore defaults ok" but nothing changes in
behavior of plotter. drivers doesn't always enable. What i do wrong?
Best regards

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/grbl/grbl/issues/1139#issuecomment-264639589>, or mute
the thread

**Comment by vladislav-konoplyev** [comment]
Thanks, now it's works for me. In parallel it became clear that it was also in a weak holding torque setting of the motors
