### ISSUE TITLE
GRBL not working

### ISSUE THREAD

**Issue by shyetman** [grbl/grbl#1149]
was cutting out a design and machine stop, there is nothing in GRBL settings, just blank, there is nothing in my X,Y,Z settings, and my home button is gone.

hope someone can help
thanks
shawn

**Comment by shyetman** [comment]
![img_2626](https://cloud.githubusercontent.com/assets/24868604/21584808/e20e18d4-d06e-11e6-960d-37cdf6f3a235.JPG)

**Comment by electrokean** [comment]
From the limited info provided, this sounds like a communications error.  The USB serial port may have disconnected.  This can be caused by electrical noise (EMI) from the motors/spindle getting back through the USB cable.  Following good grounding practices, along with use of shielded cables and cable ferrites can help.

**Comment by shyetman** [comment]
Thank you sir, after going out and moving cable I found the problem.
