### ISSUE TITLE
How to turn off the "Alarm lock" function

### ISSUE THREAD

**Issue by vyuke** [grbl/grbl#1189]
Alarm lock will be the first time the device starts, each time i must use "$ X" to unlock, I do not want this feature, whether the device can not start every time Alarm lock？
![image](https://cloud.githubusercontent.com/assets/18086671/23347692/0601f5b6-fcdf-11e6-8d45-16af2bee2490.png)

**Comment by chamnit** [comment]
@vyuke: This is intentional. If you have homing enabled, Grbl will set the alarm state if it doesn't know where it is, like upon power up. Steppers are open loop and require homing to set a reference point. If you don't want this alarm, then disable homing. If you need homing, you can disable this in config.h but I highly suggest you keep this behavior. It reminds you that Grbl hasn't been honed yet.
