### ISSUE TITLE
Possible to pre-calculate how long a Gcode sequence will take?

### ISSUE THREAD

**Issue by ajohansson-git** [grbl/grbl#1295]
Let's say I have a few lines of Gcode that I transmit via Grbl. I would like to pre-estimate how long the entire sequence would take to run.

Is this possible via some feature of the Grbl codeset?

Or would I have to manually calculate it -- for example, based on required travel distance, feedrates, acceleration parameters, etc., basically sum up how many motor steps there will be in total?

**Comment by chamnit** [comment]
No. Otherwise, everyone would do it. It's due to the accelerations during execution. You could assume perfect streaming and compute the motion plan of the  whole g-code program to get the actual time. However, you can't guarantee that will actually happen, since lots of things can slow down streaming.
