### ISSUE TITLE
How to turn off spindle in pause mode?

### ISSUE THREAD

**Issue by Evil-Nemesis** [grbl/grbl#1323]
hello there
I need to turn off the spindle when I pressed feed hold button!
how can I do it!?

**Comment by jahnj0584** [comment]
You can't and shouldn't

On Nov 26, 2017 9:55 AM, "Evil-Nemesis" <notifications@github.com> wrote:

hello there
I need to turn off the spindle when I pressed feed hold button!
how can I do it!?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/grbl/grbl/issues/1323>, or mute the thread

**Comment by chamnit** [comment]
With Grbl v1.1, you can use spindle overrides. With v0.9 and after, you can enable the parking motion that will make Grbl retract the spindle and turn it off automatically. It'll perform a re-enable and plunge when resumed. See config.h file.

**Comment by Evil-Nemesis** [comment]
I actually do that!!

**Comment by Evil-Nemesis** [comment]
I actually do that!!
for hardware button i do this:

**Comment by Evil-Nemesis** [comment]
I actually do that!!
for hardware button I do this:
uncomment this line in config.h:
#define ENABLE_SAFETY_DOOR_INPUT_PIN

and for the software button I changed this:
`
		void BtnStopClick(object sender, EventArgs e)
		{
			Core.FeedHold();
		}`
to this
`
		void BtnStopClick(object sender, EventArgs e)
		{
			Core.FeedHold();
            Core.SafetyDoor();
		}`
and it's OK!
