### ISSUE TITLE
The spindle/laser output stuck

### ISSUE THREAD

**Issue by realbukaPL** [grbl/grbl#1856]
I have a CNC shield on arduino UNO controlled by Universal Gcode Platform v. 2.0. Machine works fine, but I cannot get any output from M3 nor M5 commands. I tried it in laser mode, tried switching $30 values, try different output pins. I check output with a meter and always get 4.5V on pin D12, that goes DOWN to 4.44V when there should be output (spindle) from a program. 
I'm on it for hours now and I can't find anything wrong with connections in any combination. 

Is it some weird PWM setting? And why is it dropping this couple of milivolts? I just want a normal of and on 0-5v signal to use with my printing head. 

I don't have any alarms or warnings going off

**Comment by breiler** [comment]
Post the output from `$I`. Exactly what shield did you buy (provide a link to it).

**Comment by realbukaPL** [comment]
Thank you for your inteterest

The board is:
![1000000588](https://github.com/grbl/grbl/assets/95765686/d70fba28-2cad-4bf7-b409-1f340e586ff6)

My grlb version is 1.1h.20190830, opt v, 15,128

> Post the output from `$I`. Exactly what shield did you buy (provide a link to it).

Link is in polish and will not be of use, but I may add it is clearly the cheap version and does not look original

**Comment by langwadt** [comment]
this is the old repo, you should be looking here: https://github.com/gnea/grbl

**Comment by breiler** [comment]
@langwadt is right, the version 1.1 of GRBL is using this repository: https://github.com/gnea/grbl

But the shield that you have bought might still use the old GRBL <0.9 pin mapping.

This is the default pin mapping of GRBL 1.1:
https://github.com/gnea/grbl/wiki/Connecting-Grbl#grbls-pins

Since you didn't provide the link to the product, I will have to assume it is based on the protoneer design which expects a different pin mapping: https://blog.protoneer.co.nz/arduino-cnc-shield/#BoardLayout

**Comment by realbukaPL** [comment]
@breiler I understand, this would explain a lot. Thank you for your assistance.

**Comment by realbukaPL** [comment]
It seems the issue is mismatched hardware

**Comment by realbukaPL** [comment]
The issue has been mostely solved by adjusting settings in config.h.

enable: 
#define DUAL_AXIS_CONFIG_CNC_SHIELD_CLONE 
#define DUAL_AXIS_CONFIG_PROTONEER_V3_51
#define USE_SPINDLE_DIR_AS_ENABLE_PIN

now my clone shield works with grlb 1.1h and M3 sets pin D11
