### ISSUE TITLE
Homing with 2 Axis Machine

### ISSUE THREAD

**Issue by nfortosis** [grbl/grbl#224]
Is there a way to disable the z-axis, or at least homing on the z-axis? I am constructing a two axis machine and am hoping I can still use the built in homing function, but since it homes all three axes, it will never finish homing cycle since it will never trip the z limit switch (because it doesn't exist).

The only solution I can think of is an axis transformation: using the z axis as my x and wiring  a single limit switch to both the y and x limit pins in parallel, and using my y axis normally.

There has to be an easier way I hope.

**Comment by Zakattacks** [comment]
Sorry for digging up an old thread, but I have been trying to get this working in .9j firmware, and some of the codes seem different. I should change it to:
#define HOMING_CYCLE_0 ((1<<X_AXIS)|(1<<Y_AXIS))
//#define HOMING_CYCLE_1 ((1<<X_AXIS)|(1<<Y_AXIS))
#define N_HOMING_LOCATE_CYCLE ((1<<X_AXIS)|(1<<Y_AXIS))

instead of

#define HOMING_SEARCH_CYCLE_0 ((1<<X_AXIS)|(1<<Y_AXIS))
//#define HOMING_SEARCH_CYCLE_1 ((1<<X_AXIS)|(1<<Y_AXIS))
#define HOMING_LOCATE_CYCLE ((1<<X_AXIS)|(1<<Y_AXIS))

Right?

**Comment by Shanjaq** [comment]
Compile and Flash?  this seems like it should be a setting

**Comment by iw2fvo** [comment]
Hi to all,
I would like to use X an Y axes only for laser cutting.
I am running GRBL 0.9J and would like to understand how to disable Z axes completely and how to control laser ON OFF  from the arduino.
Any config example ?
Thanks
Regards,

**Comment by Zakattacks** [comment]
I never got it to work properly and moved on. I have seen cases where it is
possible, but I don't have enough gcode experience to get it working yet.
As for the Z axis, as long as there isn't a motor hooked up you should be
fine.

**Comment by iw2fvo** [comment]
Thanks ,
I would like to know how to wire the laser ON OFF to the arduino using grbl 0.9J.
Any suggestion is appreciated.
Ambro

**Comment by iw2fvo** [comment]
I have removed the Z wiring to the relavant stepper motor sinc I am trying to use the laser beam instead.
I understand that it is hard to have the homing cycle working properly on 0.9J: is this the final situation ?   Let me know please .
thanks

**Comment by lalo-uy** [comment]
You can wire the laser on the spindle on/off output, and control it with
M4/M5  g-codes
Be sure to disable PWM output in the compile options.

2016-06-15 4:36 GMT-03:00 iw2fvo <notifications@github.com>:

**Comment by tklus** [comment]
Or, you can connect the laser to your PWM output and you will have control of the power of the laser. this is nice for etching at lower power and then cutting at higher power. I am currently running the Jtech GRBL .9G that is set up to be used with lasers. I am also using picsender to send the gcode to the arduino. I have found picsender to work the best with the jtech version of GRBL. It has been well worth the $19.99 they charge for picsender.

check out this article that explains how to hook it all up.
https://jtechphotonics.com/?page_id=1100

Tim

**Comment by chamnit** [comment]
I'll be adding this 2-axis homing setup to the FAQ shortly, because it's been too common of a question. 
Basically, change these two lines in grbl's config.h file:

``` 
#define HOMING_CYCLE_0 (1<<Z_AXIS)                // REQUIRED: First move Z to clear workspace.
#define HOMING_CYCLE_1 ((1<<X_AXIS)|(1<<Y_AXIS))  // OPTIONAL: Then move X,Y at the same time.
```
to this:
```
#define HOMING_CYCLE_0 (1<<X_AXIS)
#define HOMING_CYCLE_1 (1<<Y_AXIS)
```

That's it. Re-compile and re-flash Grbl via the upload instructions on Grbl's Wiki page. (Link on front page).

**Comment by alexscarbro** [comment]
Given that there are now LOTS of cheap (£155) DIY CNC laser engravers for sale that use GRBL I can't help but think it may be worth adding a "DISABLE_Z_AXIS" in the $$ command list.

It'd be useful for all those that are uncomfortable with editing and re-compiling.

Just a thought,

Alex

**Comment by chamnit** [comment]
@alexscarbro : Disabling the Z_AXIS will make no difference in how a 2-axis machine works, since you are never using it. Unless you have an H-Bot or CoreXY CNC machine, which operates differently than a straight cartesian CNC, Grbl will work fine with a 2-axis machine without any alterations necessary. 

If you do have an H-Bot or CoreXY machine, Grbl doesn't officially support them, but does at a developmental level only (I don't have a machine to test on) with a  config.h macro.

That said, Grbl will remain requiring compiling and altering the config.h file for the foreseeable future, because it's very simple to alter the config.h file and recompile via the Arduino IDE. But, mainly, it can't afford to add new settings, as available flash memory is extremely limited on the 328p, especially with the new features in v1.0.

**Comment by alexscarbro** [comment]
@chamnit This request was more geared towards the homing sequence since this requires X, Y & Z limit switch activation (if I'm not mistaken) so this feature can't be used on the low cost X/Y CNC engravers without re-compilation.

Ah ha, understood regarding the 328p - I know what it's like to be counting every byte. Perhaps one day some EEPROM will be standard issue on the Arduino boards and few more parameters could be pushed in to NV memory.

Thanks again,

Alex

**Comment by sotogiovanny** [comment]
por favor puedes explicar con mas detalle donde es que se modifica el codigo grbl para el homing de solo dos ejes, no entiendo mucho sobre como modificar

**Comment by sotogiovanny** [comment]
please can you explain in more detail where the grble code is modified for accommodation of only two axes, without saying much about how to modify

**Comment by chamnit** [comment]
@sotogiovanny : Read [this](https://github.com/gnea/grbl/wiki/Frequently-Asked-Questions#how-do-i-configure-my-homing-cycle-to-just-do-2-axes-or-i-have-a-pen-plotter-and-dont-have-a-z-axis).

**Comment by CNCdood** [comment]
This is the error message im getting when im trying to upload the compiled firmware to the machine via  Audruino. can anyone asiist on what i may be doing wrong?


Low memory available, stability problems may occur.
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x0d
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x0a
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x47
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x72
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x62
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x6c
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x20
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x31
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x2e
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x31
An error occurred while uploading the sketch
