### ISSUE TITLE
Status of Limit switches

### ISSUE THREAD

**Issue by StefanHager** [grbl/grbl#240]
Hi!

Is there also a possibility to report the status of the limit switches? For example by sending a "?" command over the serial connection?

**Comment by derpston** [comment]
I'm aware this issue was closed some time ago, but I'd like to add my voice to those asking for this feature. I found the ability to query the limit switch state (after any inversion settings) very useful when setting up a Marlin-powered 3D printer, and I'd like to do the same right now as I rebuild an old CNC mill and grblise it.

It's not a big deal, but it would definitely make the commissioning process easier.

**Comment by chamnit** [comment]
@derpston : It's a compile-time option in v0.9i edge branch. Soon to be pushed to master. It displays the binary of the limit and control ports. Not very user-friendly but usable.

**Comment by derpston** [comment]
Nice! Thanks!
