### ISSUE TITLE
What are people using for cutter radius compensation?

### ISSUE THREAD

**Issue by unicornswag** [grbl/grbl#385]
Like the title says, I'm curious as to how (or if) people are implementing cutter radius compensation in their work with grbl. Since the standard G41/G42 codes are not currently supported, it would need to be handled by the cam software or some sort of post-processor that alters each coordinate to match the tool. Most simple 2.5D CAM software such as dxf2gcode either don't do offsets at all or use G41/42. I may end up writing a shell script that can convert standard g-code with no offsets to tool-specific code with a specified left or right offset. Unless there is an easier way?

**Comment by bwoostdam** [comment]
G41 and G42 are absolutely crucial for using GRBL.   I use a modern day diode laser cutter, coming from an industrial machine and can't believe there is no support for these G-codes.. Actually this must be totally unacceptable to many users.  Please please implement G41 and G42 into GRBL !!

**Comment by scottrcarlson** [comment]
The terms "totally unacceptable" for an open source volunteer driven
project is an interesting choice of words. Do you understand that this
isn't a product that is being sold to you? How much did you pay for GRBL ?

Feel free to review the completely free and open source code and make
whatever modifications you dream of.

None of the contributors for this project get any form of compensation. If
this is something you need, then you could a) do it yourself, b) hire
someone to do so, c) ask in a really better way to see if someone would be
willing to drop what their doing and perform this work for you free of
charge.

-Scott

**Comment by pharmerai** [comment]
Reviewing the history of this issue,  GRBL running on the Arduino is an exercise in optimization and priority. There simply isn't enough resources on the chip to perform every feature, this is likely the reason why it was not implemented.  

See above comment. Porting this to a larger micro with more resources would allow likely many features that are not currently implemented.

The solution above is to simply use the vary capable CAD/CAM Post processor to generate the modified gcode (as a work around).

If you think about it, it's super impressive that all of this runs on an Atmega 328p that costs < $25.

I know there was some efforts many years ago to port this, I'm not sure where it's at, I haven't gone back to look...

There might be some compelling hardware now that we are 10 years into the future when this issue was first created.

**Comment by scottrcarlson** [comment]
Reviewing the history of this issue, GRBL running on the Arduino is an
exercise in optimization and priority. There simply isn't enough resources
on the chip to perform every feature, this is likely the reason why it was
not implemented.

See above comment. Porting this to a larger micro with more resources would
allow likely many features that are not currently implemented.

The solution above is to simply use the vary capable CAD/CAM Post processor
to generate the modified gcode (as a work around).

If you think about it, it's super impressive that all of this runs on an
Atmega 328p that costs < $25.

I know there was some efforts many years ago to port this, I'm not sure
where it's at, I haven't gone back to look...

There might be some compelling hardware now that we are 10 years into the
future when this issue was first created.

-Scott

**Comment by bwoostdam** [comment]
Yes, you are right. I apoligize for the wording. But I would like to explain myself a bit more. As an avid RC modeler I took to flying racing quads besides airplanes. I have seen the development in that field and we went from a Model T-Ford (awsome in its time) to a High-End SUper car in a mere 5 years or so. I declined the 3D printers because the things produced were for several reasaons not useable for me. I heard fellow modelers stories about how the driver boards progressed and the steppermotors become quiet because of higher driving frequencies because of the introduction of 32bit. I thought, just as with drones, that the MCU had been upgraded to a more capable model. Apparently I am wrong. I wrote my own geometry analysis software (gcode generator) for AutoCAD (and alike) and it functions well, but... totally depending on the assumption that G41 and G42 were possible. It never occured to me that the millions of 3D printers, vinyl cutters, laser-engravers (cutters) are all (still) running on the Atmega. As I am not capable of joining in on the GRBL delevopment I will investigate the complexity of implementing G41/G42 in my own code. Thank you for your response and enlightenment. I hope someone will have a bright idea on how to implement this in GRBL. As the number of diode laser-engravers(cutters) is rising, the need for it might inspire some new developments. Besides, I am surprised to learn that all these 3D printers etc. worldwide are running on the free GRBL. That makes it an AWESOME achievement. Apologies indeed well deserved and given.

**Comment by AlexHolden** [comment]
I believe the most common port of grbl to 32 bit ARM processors is grblHAL: https://github.com/grblHAL
There is also FluidNC for ESP32 processors: https://github.com/bdring/FluidNC
They both have lots of additional functionality beyond the 8 bit version of grbl (which is really limited by the amount of memory on an AVR), however I don't know if either of them support G41 and G42. It isn't a feature I have ever needed.

I think most modern 3D printers use firmware like Marlin or Klipper that has lots of extra 3D printing specific functionality.

**Comment by scottrcarlson** [comment]
Implementing G41/G42 on the current device is probably never going to
happen. Porting it to another device and expanding its features will
require some serious time and dedication.

In the meantime, if you're trying to get some production off the ground,
you could take a look at the likes of Mach4 (Has extensive G/M-Code support)
https://www.machsupport.com/wp-content/uploads/2014/05/Mach4%20Mill%20GCode%20Manual.pdf

If I see anything out there, I'll drop a line, there have been some forks
of this project, but nothing I've seen has really gained traction.

-Scott

**Comment by bwoostdam** [comment]
Thank you all for your suggestions. I did look at GrblHAL but as an former MCSE I already realized beforehand what HAL means. Reading the documentation confirmed that GRBL itself is not different. The HAL was created to prevent forking of the source.
I will take a look at Mach4.  I have looked into hte complexity of G41/G42 at a 2D level. I think I solved it and am working on implementing it into my code. In the future my code will be available on a website I plan to put together. Maybe end of this year. Although in 2D in the positive XY quadrant it is not really complex, it does require enough memory and indeed quite a few added lines of code. I can understand why it does not fit into an ATMega.  I do think it would be a good thing do fork GRBL into an 32bit version. When I look at OpenTX and EdgeTX and CleanFlight and BetaFlight, FreeCAD etc.  users do not mind switching to another fork if it has real benefits.

**Comment by AlexHolden** [comment]
grblHAL is a fork of grbl that supports many 32 bit processors, has lots of additional features and improvements, and is still under active development. You are mistaken if you think the core is no different from that in the 8 bit version of grbl. The documentation describes it as "a rewrite of grbl 1.1 aimed at 32-bit processors".

**Comment by bwoostdam** [comment]
Then I need to invetigate further.  I read this: https://www.grbl.org/what-is-grblhal
