### ISSUE TITLE
Arduino Zero on the horizon...

### ISSUE THREAD

**Issue by Protoneer** [grbl/grbl#404]
Interesting options are opening....

http://arduino.cc/en/Main/ArduinoBoardZero

Flash Memory    256 KB
SRAM    32 KB
EEPROM  up to 16KB by emulation
Clock Speed 48 MHz
Footprint similar to Arduino Uno

**Comment by Cinezaster** [comment]
This could be a nice platform. 
https://www.kickstarter.com/projects/1204283/zeropi-arduino-and-raspberry-pi-compatible-develop/description
https://github.com/Makeblock-official/ZeroPi

A port to the arduino zero would do the trick?

**Comment by langwadt** [comment]
www.st.com/stm32nucleo

2x speed, 2x flash, 3x ram, M4 with FPU, 1/4 price

**Comment by kfoltman** [comment]
I think one of the Nucleos is a great idea. They're cheap and some of them are fairly powerful. I have some good experiences with STM32 microcontrollers. On those particular boards and the discovery series the ADC input routing can be less than great in terms of digital noise sources around the analog tracks, but that shouldn't be a disqualifying factor for CNC uses.

**Comment by Cinezaster** [comment]
Still you would need an extra shield for the stm32nucleo. 
Never the less, the nucleo sounds like a capable microcontroller, maybe <a href="https://github.com/synthetos/TinyG/wiki/What-is-TinyG">tinyG or G2</a> are beter suited for using that power. It can handle 6 axis and has Constant jerk acceleration planning (3rd order S curves) for smooth and fast motion transitions. something grbl doesn't have.

**Comment by chamnit** [comment]
@Cinezaster : Yes. This board looks nice. I have several plans on how to proceed into the ARM world, which include 4+ axes and a lot of things that other motion controllers do not have (and probably won't anytime soon due to their size). Much of this is already done, but unreleased.

There multiple problems with going into the ARM world. The main one is that everyone has their own strong opinions on which ARM controller to use. And none of them seem to be the "right" one. But, the truth is that any one of them will work. You don't really need a Cortex-M4 FPU to do CNC tasks. It's way overkill and usually leads to bad coding practices. The proof is in the pudding, so to speak, as Grbl runs very well on a 16MHz AVR still. 

It's hard to see how 10x-20x more CPU power will change what Grbl does, based on its philosophy on doing its motion control task and not much else. Any additional stuff can very easily be handled by an additional, cheap MCU or GUI.  Even if there are more floating point operations with additional features, this doesn't quite justify the need. The SAMD21 on the ZeroPi and Zero are still more than enough to start with.

**Comment by dileepplayer** [comment]
hello everyone., I bought this(link below) board for a project, and i'm attempting to port grbl to this board.It board costs $12.99 and includes an on-board emulator.

any suggestions before I start?? please let me know.

http://www.ti.com/ww/en/launchpad/launchpads-msp430-msp-exp432p401r.html
