### ISSUE TITLE
Random freezes when moving small steps

### ISSUE THREAD

**Issue by kikigey89** [grbl/grbl#444]
Hi!

First of all thanks for this nice piece of software :-)

I have a strange problem: When moving small steps (for instance when milling a small gear with 25 mm diameter) sometimes I get random freezes. I tested this with 0.9c, 0.9f and 0.8c. Sometimes it works but mostly not. In 0.9c and 0.9f the freezes only happen when milling the teeth. Before I mill a center hole and with 0.8c it freezes mostly when the end mill moves down for the first tooth after it milled the center hole.

I had a similar problem in the past but I found out that I got some kind of noise on my limit switches as the cables run in parallel to the stepper cables. I could solve this by putting a capacitor between the Arduino input for the limit switch and ground. But for this issue I already disconnected all external connectors. So only USB, power and the steppers are connected.

Sometimes it stops at the same position as before. But not always. I also tried different feeding speeds, all with the same result.

I tried different computers and softwares (also different versions) as well. The only remaining thing is grbl. I could notice that at a certain point the software stops sending commands. No idea why. grbl does its job till the last sent command has been executed. Then it stops.

If you need more information, let me know! And if I can test something to find the problem, let me know as well!

Best regards,

Chris

**Comment by kajackdfw** [comment]
I also experienced this freezing after reducing a circle from 3cm down to 9mm. It froze in the 3rd quandrant ( 270 to 360 degrees ). I overcame problem by removing the J method arc, and replacing it with a series of straight cords. You can see what I commented out in the circle routine of this file. json_to_gcode.py ( https://github.com/kajackdfw/python_gcode_writer )

**Comment by chamnit** [comment]
@kajackdfw : Could would elaborate on this arc freezing problem you encountered, like if it generated an error or just froze everything? 

I'm unaware of any existing problems with the arc algorithm in Grbl, but would like to know if you found a new one. What version of Grbl were you using when this problem occurred. And can you supply a repeatable example with the '$' settings? Thanks.

**Comment by CaptainFeature** [comment]
I know I am a bit late but this thread was the one I went through again and again trying to solve my issues. 

I am working with a self made milling machine using grbl on an arduino uno as interpolator and the shapeoko grbl sender on my windows pc. I also had these anoying stops every now and then. They occured mostly at sections with very short distances between points.

From the beginning I used shielded cables. Desperate to use my mill without having to press nc start every now and then I tried almost everything I found in forums. I used smaller feeds, checked for noise issues, created nc code without arcs (which made it worse) checked my pc's power saving options and so on. I even programmed a tool to thin out my nc code at sections with short distances. Nothing really helped.

Yesterday I came across [universal gcode sender](https://winder.github.io/ugs_website/download/). I installed it rather because I liked the user interface than to solve any problems. But suddenly the issues were gone. No stopping anymore. 45 minutes of uninterrupted milling - at last.

I hope this helps nc enthusiasts with similar issues.
