### ISSUE TITLE
Freezing, resetting, more random problems

### ISSUE THREAD

**Issue by thrushd** [grbl/grbl#483]
Hello,

I am completely out of ideas for the below list of issues I have been having ever since I upgraded my cnc (mechanically, ball screws instead of belt). it was working perfectly before the upgrade, now I cannot get through a single gcode file except if I remove all of the Z movements. The main recurring issue is that when streaming a file to grbl (any version) with grbl controller (also any version, I have tried them all) it will get through about 10 to 20 lines and then stop. Usually this happens when the Z axis moves but not with all gcode files. It will either freeze outright, or reset and try to continue at a new point in the file. 

Troubleshooting I have tried:
-Different builds of grbl (all of 0.8, 0.7, and a few 0.9)
-Different version of grbl controller
-Streaming the code through the simple python script, mixed results, usually works if it is just the arduino, no shield
-Different CAM post processors, Solidworks with HSMXpress doing CAM
-Isolating EMI, different USB cord, shielded USB cords, etc. I took my setup home as well since the building I work in does have a lot of noise, same result
-Different control boards, I am using a custom grbl shield, I have rebuilt it twice now.
-Pull up resistor (10K) on the soft reset
-Better stepper power supply, noise free
-Different Arduinos
-Different Computers

I think there is more but it is all an angry blur at this point ;) The most infuriating thing is I had it working perfectly before I did those upgrades, now its super grumpy. Any and all input greatly appreciated.

**Comment by ClarkDailey** [comment]
My DIY CNC end mill uses GRBL v1.1 Arduino AtMega2560.  The end mill is a heavy duty Grizzly G1006 with off-the-shelf stepper motors, drivers, and a custom Arduino CNC shield.  I ran into a problem when cutting one-hour 3D relief carvings.  It appeared that GRBL would freeze at random times, and would not accept any more commands from the Universal G-Code Sender program running on my laptop.  In order to debug the problem, I added 3 LEDs and hacked the GRBL firmware to toggle them.  The red LED is toggled in the stepper motor interrupt routine (ISR) every 1000 steps.  The yellow LED is toggled every line motion cut (mc_line subroutine).  The green LED is toggled whenever GRBL checks for a byte on the serial port (protocol_main_loop subroutine).   Running another one-hour job, motion again froze, as usual.  The green LED was still toggling and checking the serial port, which indicated to me that the GRBL firmware was not frozen, but the communications hardware was latched up.  Unplugging the USB cable at the laptop side, and plugging it in again, the 3 LEDs went through the boot-up process, which indicated to me that the Arduino microprocessor rebooted, and all positioning information was then lost.  This proved to me that it is was electro-magnetic-interference problem on the USB cable.  I use a gutted desktop computer case to contain the Arduino, the power supplies, and stepper motor drivers.  The wiring is clean.  No motor cables or power cables are close to the USB cable.  To continue testing, I replaced the shielded 2 foot USB cable, with a 2 foot USB cable with ferrite beads on both ends.  The iron ferrite beads are inductor chokes that filter out high frequency RF generated by the motors and electronic chopping circuitry.  This did the trick.  I have run several one-hour CNC jobs without any motion freeze.  Random problems caused by EMI are difficult to solve, but I think this one is solved for me.  There are a number of postings on the internet describing this GRBL freezing problem.  Although GRBL is taking the rap for this, it is not the problem.  The Arduino could benefit by adding some filtering on the USB differential signals, but this would add cost.   So the filtering has to be done on the front end cabling.  Hope this helps anyone having this problem.

**Comment by grahamsatgithub** [comment]
I fixed mine by connecting a USB cable directly to the board. It has the 5v, GND, D+ and D- brought out onto the back so I soldered a shielded wire on and added a USB-A plug on the other end. Problems all solved. I also added a 0.1uF capacitor to the motor. Probably helped but it wasn't the main cause.
