### ISSUE TITLE
Futur dev : G5 ?

### ISSUE THREAD

**Issue by ledahu** [grbl/grbl#509]
Hi

i wonder if the G5 implementation is in dev ?

**Comment by fenderrex** [comment]
Why you need to reopen this not to seem shrewd.
Hmm well it seems that the STM32F407 and grbl have met(on GitHub). Tom imported the v1.1? over and achieved six axis synchronous control. https://shop.tomsrobotics.com/product/grbl32-6-axis-cnc-controller-g6f4-500khz/.  I believe this information belongs here because in order for a sixaxis robotic arm to be able to mill it still needs frequency coordinated steps perhaps simply increasing the look ahead for this chip couldn't improve acceleration for the extremely small segmentation? No the serfice finish! However g5 is largely used by Enterprise controllers to maintain tolerance and throughput that is required for government contracts(high feed no chatter). I believe that optimization would best be suited utilizing a 3D spline that could be executed by 6 transform aka g5. It would be nice to see a set of translation classes for things like polar coordinates and triangular coordinates (for Delta printer and that cool new 6axis Delta printer) into Cartesian coordinates on the step driver. A workaround for me without building g5 support to match fusion 360 post processor would be to make a frequency/step offset map. Having all the motors sync up step per step works perfect in a Cartesian set up the moment you go to polar coordinates you must know what angle you are currently maintaining while you move to the next location.. I know I read something about backlash support if that is anything like Mach 3 ball screw warp adjustment perhaps I can adjust it for my needs? Bottom line is I am very curious in the g5 and g5 sub commands on multi-axis given that arcs are limited to singular geometric planes any robotics arm trying to draw a square box in midair will have a very hard time running with the current software if you do not ever intend on supporting g5. High-precision contour control or G07.1 cylindrical interpolation https://en.industryarena.com/forum/g7-1-fanuc-10t--125701-2.html
