### ISSUE TITLE
Resuming after soft limit without homing cycle

### ISSUE THREAD

**Issue by matthijskooijman** [grbl/grbl#556]
- When soft limits are used, doing a homing cycle after startup is mandatory.
- When a soft limit is triggered, a soft reset is required to continue.
- After a soft reset, a homing run is again required, even though the machine position is not lost.

I realize that you can do a `$X` to unlock grbl after the soft reset, but that command is really something that is marked as unsafe and shouldn't be normally used.

Is there any other way to more elegantly deal with soft limits? If not, should one be added?

I mostly ran into this while jogging manually, where I'd like the soft limits to prevent me from jogging too far, but then continue to respond to subsequent jogging commands. When playing a full gcode file, I guess this is different - it shouldn't just continue with the next command when the previous command would end up past the soft limits.

**Comment by cri-s** [comment]
After running in softlimits, normally reset and homing cycle is needed.
You must different between two distinct softlimits.
1) cnc is computing move and realize that end position is outside softlimits and hits softlimit alarm.
2) cnc moves outside softlimit during G code moving.
Most softlimits fall under point 1, but some are point 2.
If softlimit type 2 happens, without reset (including trashing homing position) the softlimit stil persist
and it's not possible to exit from it.
Example for type 2 is probing, offset changing, moving with some dynamic compensation in effect.
I have added jogging interface to protocol.c in order to get out limit switches.
Constant velocity, direct pin manipulation and delay_us for axis movement, no position update
and raising alarm for inhiibiting any further programmed move. It works for it purposes, but won't
work for things like softlimit as it not change the actual position variables.
It could update position variables, but then backlash compensation, stopping and jogging on relative coordinates, softlimits, hardlimits, all this working anymore during or after jogging.
both trashes

**Comment by chamnit** [comment]
@cri-s : Grbl checks all motion commands, except homing, if the commanded motion exceeds the machine travel limits. This covers both your suggested soft limit modes. There's no reason to make it more complicated.

**Comment by cri-s** [comment]
after have issued ctrl-X $X you must issue g92 with the MPos coordinates from ? command.
Then it's possible to continue.  I have added gc_sync_position() to mc_reset in order to not needing
this and not loosing the position after the stop/abort command. g92 is a workaround and have side effects.

Because the non conformance implementation of coordinate spaces, and because i was too lazy to
correct it, i have received many such softlimits.
If softlimits trigger, mc_line limits movement to softlimit + 1 step and waits until
state is IDLE, then checks if sys.position is greater then softlimit and only in this case trigger it.
This have saved some cuts that otherwise are damaged.
 
I propose the following commands:
$K for key option, same as pressing the key it should return the actual settings.
$KS for stop 
$KP for pause
$KK for kill , kill the current planner_current_block , needed for jogging, maybe on $K0 kill all, $K4 kill 4 blocks, $KK is alias for $KK1
$KOO for option flags example: $O=1 or $O3=0  for the 9 optional slash ignore option. $KOO=$KOO1
$KOF feedrate overriede from 0-150, same as the diode/potentiometer/switch compinatio on analog port.
$KOS spendle override,
$KOC coolant override

Hover a stop command is missing.
Instead of reset, stop should be possible to use, that raises alarm, no stepper enable pin shutdown,
and after some seconds, clear the critical alarm, clear planner buffer and serial buffers, resets gcode
state (g0/g80, ....) maybe one line from eeprom that is issued at startup too and can be edited by
the user removing the inch/mm eeprom setting as example, and leave state in hold state.
The same should be issued after ctrl-x and $X using maybe $S .
Actually on reset, the position is remembered correctly on ? command, but the next move thrash it.
Issuing g92 command with the values displayed let adjust the position and let one continue without
position errors introduced with homing switch tollerances.
It is possible that one must disable softlimits with $20, go to pos 0, reissue ctrl-x, $X enable softlimit
if one want continue with softlimits correctly set.
Actueally it makes more sense to connect stepper-enable to stepper-sleep, invert it and set
stepper-idle-lock-time.
If stepper-idle-lock-time is at 255, then it is possible to resume.
After ctrl-X and $X
The ? command gives out the remembered coordinates for machine pos.ver
use g92 to set it, because otherwise on the next move this are lost.

**Comment by cri-s** [comment]
after have issued ctrl-X $X you must issue g92 with the MPos coordinates from ? command.
Then it's possible to continue. I have added gc_sync_position() to mc_reset in order to not needing
this and not loosing the position after the stop/abort command. g92 is a workaround and can have side effects.

For Jogging, if only in idle state, it's simple.
If you want that code, only idle state, then i extract the patch.
! stops the jogging
command is
$JX or $J-X , only one axis at time and fixed feedrate.
but it works only in idle state.

**Comment by cri-s** [comment]
Do you want a patch to not need homing after ctrl-x ?

**Comment by cspwcspw** [comment]
Today I just implemented homing and soft limits and I also found the two steps needed to clear the Alarm (Reset, then sidestep or perform homing again) a bit messy.  But I think I agree with Chamnit's point of view: the GUI can easily cope with the two steps if it needs to.  

More generally, I think the grbl project would be better served by "assuming" that it had an intelligent front-end pre-processor / sender that also kept state and , and then asking "what functionality should/could we reasonably migrate into the front end on the laptop/host?".   It feels to me soft limits should be enforced long before the g-codes are even streamed to grbl, so I'm not convinced soft limts should even be in "core" grbl.  (Certainly I would kick them out if they take up space and processing cycles that could more profitably be devoted to "real grbl strengths" like acceleration, planning, cornering, etc,")    And then of course, pre-processing in the host could implement all the extra things like subroutines or peck-drilling. I might also like extra features like having soft limits on the work area rather than only on the machine limits.  So if I mount a small PCB on a bigger table and set some work coordinates, I don't want to go drilling outside the soft-limit bounds of the PCB.

**Comment by chamnit** [comment]
@cspwcspw : I strongly disagree. IMO, safety protocol should be done on the motion controller and not depend on a GUI, which can be within a wide range of "plain doesn't work" to "intelligent". There are too many things that can go wrong that will go wrong. 

Soft-limits are on Grbl's side for one particular and important reason. G-code parsers can be ever so slightly different. Some with bugs or others that use a different g-code dialect. If these motions are still passed to Grbl, it's possible for a machine to exceed the soft-limits unintentionally. However, there is nothing wrong with having two levels of checks, where the GUI does one and Grbl still does its own. 

Second, a soft limit alarm does not require re-homing, even though it looks like it does. Just unlock the Alarm and you can resume operation like normal. This is because soft-limits performs a feed hold before throwing the alarm. Feel free to test this.

**Comment by cspwcspw** [comment]
Sure, it works as you say, and that is how I am clearing the error.  (I don't need to redo the homing cycle).  I think the initial niggle of the thread (admittedly a very minor point) is that the "soft limit error" tends to behave like a "hard limit error", whereas in reality, they are different.  If I have not set a feedrate on a G1, for example, I get an error, but not one that requires two steps to clear,  

As for whether to think about the long-term future of grbl as "only what runs on the back-end (say an Arduino)", or as a "front-end G-Code pre-processor/driver and streamer + back-end combo working together", either could work.    Already in grbl, it seems that you have two loosely coupled "processes" for parsing and planning and putting things in the block buffer, then the ISR process that does the motion on the motors.  Perhaps there are possibilities for different decompositions: might one be better off, for example, planning the blocks and decoding the G-code before moving blocks across the USB interface to the Arduino?  

I think it might be fun to try.

**Comment by chamnit** [comment]
@cspwcspw : The soft limit error is not an error but an alarm. These are treated and should be treated differently. Two steps (a reset and unlock) for acknowledging and canceling an alarm is not a huge deal in my opinion. In general, you shouldn't be running into soft-limits constantly, and, if a job might come close to a soft limit, I would make sure to do a dry-run by streaming the g-code program in Grbl's check mode. It'll throw a soft-limit alarm if the program exceeds machine travel without moving the machine.

I thought about decoupling Grbl a while back and decided against it. G-code streaming is a very clean separation between the controller and a GUI. You don't need a lot of comm bandwidth or need to invent a new protocol, which accomplishing something very similar to g-code already.

**Comment by mkeyno** [comment]
@chamnit  the `soft limit alarm`  very annoying whenever you  power up & run homing cycle and intend to run CNC job , but the `soft limit alarm` appear and ask for `reset to continue` and when sent soft reset command the message [$H |  $X  to unlock ] re appeared again and should redo the last command.!!!
@chamnit  I'm former user of Marlin firmware, I used simple task to run my CNC job, just homing and go whereas hard/soft/homing cycle enabled, is there any way to use GRBL in same easy manner ?

**Comment by chamnit** [comment]
@mkeyno : Please understand that Marlin and Grbl are servicing two different CNC machine types. Marlin is 3d printers, and Grbl is CNC mills and routers, which are much more dangerous than printers. Larger machines can break tools or flig metal workpieces across the room if a small error occurs. I know that the soft limit alarm is annoying, but it works the way it was designed. To prevent exceeding max travel DURING a job. If you are jogging, the soft limit alarm is easy to invoke, which is why in Grbl v1.1 I created the jogging command set. These ignore the soft limit and just prevent the offending motion from being executed. So your problem has already been addressed and this matter is closed.

**Comment by mkeyno** [comment]
thanks @chamnit I'm aware of  your purpose and your comments in other issue, but honestly I've already use special version of marlin in my cnc laser but during last days I've tried to replace it with GRBL .9j & 1.1f ,and yet  I couldn't find any proper setting to homing and running cnc job , it would be nice if there is forum which is successful installation shared, I really appreciated if you could create troubleshooting/ wiki page for such effort

**Comment by chamnit** [comment]
@mkeyno : There already is. See [here](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#quick-guide-to-setting-up-your-machine-for-the-first-time), [here](https://github.com/gnea/grbl/wiki/Wiring-Limit-Switches), and a preliminary [wiki page](https://github.com/gnea/grbl/wiki/Set-up-the-Homing-Cycle) on setting up the homing cycle, which I requested some help on [here](https://github.com/gnea/grbl/issues/156), since I don't have a lot of time at the moment. Also Google is your friend. There are plenty of other resources on this topic, like at the old shapeoko wiki and numerous issues threads here.
