### ISSUE TITLE
QUERY: Does anyone DISABLE the auto_start setting?

### ISSUE THREAD

**Issue by chamnit** [grbl/grbl#557]
**All:**

I've been busy working on fixing Grbl's state machine and need to get an idea of usage of the auto_start setting. Does anyone disable this auto_start setting? If so, can you give a description of how you use it and what you use it on?

The reason I ask is that I'm contemplating removing this setting and have Grbl always assume every command it receives will be executed as soon as possible. This simplifies the state machine greatly. IMHO, GUIs are better suited in managing what is sent to Grbl and when. Thoughts?

**Comment by philmcmillan** [comment]
@chamnit - I have built a standalone, non-gui controller that runs off of an ATMega so that I don't have to have a laptop of other computer hooked up. I disabled autostart because I want to explicitly require the operator (me) to push the go button after the controller software starts reading the file from the SD card and streaming to the GRBL controller through the serial connection. It's basically an additional safety check that I've built in to my controller.

**Comment by LotusPack** [comment]
@philmcmillan can you share your controller software, it would save so much time?  I am designing a HID with DRO and SD to store the g-code.  I am using the controller for ATC and as you are also streaming the g-code for each tool to GRBL. That structure works perfectly as I can keep all tool offset lists in the controller.

**Comment by panmaneecnc** [comment]
please see at https://github.com/panmaneecnc/sd-card-gcode-sender-for-grbl 
now i try to develope for tool change . you can follow us . thank you

**Comment by faultylee** [comment]
I'm a newbie in CNC, adding those buttons are in my coming plans. If auto_start is removed, I'm wondering if I can use Feedhold, but holding it with a toggle switch to manually start it?

**Comment by philmcmillan** [comment]
@LotusPack I've got it here on github https://github.com/philmcmillan/shapeoko-controller/tree/develop. It's still in development and I've not really finished debugging the current state (work got silly for the last 7-8 months); but you'r welcome to it. I've got it under the MIT license, so it's open and I'm happy for folks to take it and run with it. I'd only ask if you find bugs or have better ideas to let me know, give me a patch or pull request.

**Comment by chamnit** [comment]
@philmcmillan : Point noted. I thought about the impact of this before posing this query, but it still should be the job of the host GUI to stream g-code to Grbl. This fact is basically a cycle start in itself. The only thing Grbl needs to do is resume from a feed hold or a program pause with some kind of command. The plan is use the current 'cycle start', which doesn't describe what it does very well,  as a 'resume' command, which resumes holds.

@faultylee : Feed hold should work exactly the same. The cycle start button will still work, except it'll work as a resume functionality for the holds.

**Comment by philmcmillan** [comment]
@faultylee essentially you are correct. The M0 mandatory pause would stop the controller from executing  additional instructions until you hit the go button.

**Comment by philmcmillan** [comment]
@chamnit - I understand and think you're reasoning is sound. I'm happy to make the change in my practice. Short term I'd probably use an M0 and resume as secondary mechanism for controlling cycle start. Until I fixed my wiring harness and controller firmware.

My initial hardware design was bit naive since I'm pretty much a CNC noob (I've learned a lot from building my own controller) so my cycle start was basically hitting OK on the keypad when selecting the file to send. I really should fix that so that the controller interface requires and explicit separate GO prior to opening the stream.

**Comment by doppelhub** [comment]
We handle cycle start in software.  It's always a difficult decision to remove an industry feature, but if it allows other great things instead (more G38.x probe commands, jerk interpolation, etc), I'm game.  It'll also free up pin A2 for other things.

**Comment by chamnit** [comment]
FYI, Grbl v1.0 will no longer have auto cycle start as a setting. It will always assume it's enabled. Closing this thread.

**Comment by paulkaplan** [comment]
Any idea on a release date for 1.0 @chamnit ?

**Comment by chamnit** [comment]
@paulkaplan : Probably summer to fall. I'm trying to stick to a somewhat annual release cycle.

**Comment by paulkaplan** [comment]
Is there a feature set and / or branch for it?

Easel was slow to grbl 0.9 (about to release full support for it), so I want to be faster on grbl 1.0!

**Comment by chamnit** [comment]
@paulkaplan : There is a grand plan, but nothing released at the moment. Stay tuned.
