### ISSUE TITLE
Support for discrete stepper drivers and H bridges

### ISSUE THREAD

**Issue by nullsub** [grbl/grbl#56]
Hi,
I am currently using grbl with 2 ULN2003 transistor arrays(per stepper). 
The steppers are connected like this http://ssecganesh.blogspot.com/2008/05/driving-stepper-motor-using-uln2003.html
I tested my code also with a L293D H bridge and it works well. This could lower the price for a grbl stepper driver board.

Is this feature welcome in grbl? It would need a config option which decides whether to compile the stepper driver or the H bridge code.
Thank you

**Comment by DanielePas** [comment]
Does anybody know how this story is ended (if it ended)? I'm trying to find some informations about how to use grbl with ULN but it seems nobody worked on this lately... but I also find no info about previous versions someone talks about that are able to do something.
Thanks.

**Comment by cri-s** [comment]
it is easy, but instead of 2 pins, 4 pins are needed, and maybe enable
need to be pwm
pin too in order to use higher voltage with pwm.

2015-02-27 20:25 GMT, Daniele Pasciuto <notifications@github.com>:

**Comment by cri-s** [comment]
http://arduino.cc/en/Reference/StepperUnipolarCircuit
for 3 axis stepper, you could use on hex inverter ic instead and then
you need only
two uln instead of 3 and no resistors. Further 4 uln are free or if
using uln2003 2 uln are
free that you can use for relais.
The sequence is:
 Step C0 C1
     1  0  0
     2  0  1
     3  1  1
     4  1  0
Where C0 is dir and C1 is step pin
STEP_PULSE_DELAY must be commented out

you must change this code :
if (st.counter_x > st.exec_block->step_event_count) {
    st.step_outbits |= (1<<X_STEP_BIT);
    st.counter_x -= st.exec_block->step_event_count;
    if (st.exec_block->direction_bits & (1<<X_DIRECTION_BIT)) {
sys.position[X_AXIS]--; }
    else { sys.position[X_AXIS]++; }
  }
to this, and for the other two axis too substituing X with Y and Z:
if (st.counter_x > st.exec_block->step_event_count) {
    st.step_outbits |= (1<<X_STEP_BIT);
    st.counter_x -= st.exec_block->step_event_count;
    if (st.exec_block->direction_bits & (1<<X_DIRECTION_BIT)) {
#ifdef UNIPOLAR
    uint8_t t; t=STEP_PORT; // assumes STEP==DIRECTION PORT
    bit_false(st.dir_outbits,bit(X_DIRECTION_BIT));
    bit_false(st.step_outbits,bit(X_STEP_BIT));
    if(bit_false(t,bit(X_DIRECTION_BIT)))
bit_true(st.dir_outbits,bit(X_STEP_BIT));
    if(bit_true(t,bit(X_STEP_BIT)))
bit_true(st.dir_outbits,bit(X_DIRECTION_BIT));
#endif
 sys.position[X_AXIS]--;
}
    else {
#ifdef UNIPOLAR
    uint8_t t; t=STEP_PORT; // assumes STEP==DIRECTION PORT
    bit_false(st.dir_outbits,bit(X_DIRECTION_BIT));
    bit_false(st.step_outbits,bit(X_STEP_BIT));
    if(bit_false(t,bit(X_STEP_BIT)))
bit_true(st.dir_outbits,bit(X_DIRECTION_BIT));
    if(bit_true(t,bit(X_DIRECTION_BIT)))
bit_true(st.dir_outbits,bit(X_STEP_BIT));
#endif
sys.position[X_AXIS]++;
}
  }

and on every line where is
DIRECTION_PORT =
you shoud enclose it to
#ifndef UNIPOLAR
 DIRECTION_PORT =
#endif
except for code inside st_reset()
And of course don't invert step and dir pins.

This should be sufficient.


2015-02-27 20:39 GMT, Cri S <phone.cri@gmail.com>:

**Comment by AutomatedPumpkin** [comment]
ygornac, did you ever get that to work? Your set-up looks identical to mine and I wonder whether you managed to get it using GRBL. Would be very cool if it worked.

**Comment by langwadt** [comment]
@cri-s That circuit is horrible, you'll have to run it at very low voltage and be uselessly slow, or turn up the voltage and have the transistors will self-destruct in seconds  

Most steppers are  a few ohms and the need constant current drive at anymore than a few volts of supply and a high voltage constant current drive is needed or they will be dead slow.

**Comment by dpw19** [comment]
Hi, some people use other arduino to make a uln2003 driver to have a STEP, DIR, behavior. 
It's a good solution.
For two axis:
https://github.com/latonita/SoftwareStepDirUnipolarDriver/blob/master/SoftwareStepDirUnipolarDriver.ino#L46
And for tree axis:
https://github.com/latonita/SoftwareStepDirUnipolarDriver/commit/3b91208796059db8a78692fce33510316398b30c

**Comment by whitetd** [comment]
No it's not. Far better to use stepper driver modules. Built in protection
et. And uses a lot more pins to interface.
