### ISSUE TITLE
There's no general questions area so I make issues :)

### ISSUE THREAD

**Issue by timryder** [grbl/grbl#638]
Is it necessary to use "M2" at the end of a program with grbl?  Does it benefit me in any way?

**Comment by chamnit** [comment]
@timryder : No, it's not necessary to have an M2 at the end of a program for Grbl. It's traditionally used to reset the machine during production, so all you need to do is hit cycle-start again to repeat the g-code program after the operator has placed a new piece of material in the machine. Since Grbl is not a complete controller (requires a GUI), M2 is something that both Grbl and the GUI should be handling together. Grbl only does the reset part, while the GUI does the g-code program reload and get it ready to re-send.
