### ISSUE TITLE
Using Fourth Axis

### ISSUE THREAD

**Issue by ArtificerJon** [grbl/grbl#643]
I am a newbie and am awaiting the delivery of my stepper driver shield and drivers but have been trying to find how the fourth axis is used in practice a situation which I will want to achieve but cannot find anything other than "cloning another axis" which means nothing to me.  Can someone explain, preferably with an example, where the fourth axis is linked to a rotary axis (axis A) which will move while also moving in the longitudinal (axis Y ?) axis to form a cylindrical spiral.  Can this be done without the need to unplug or disable one of the other axis ?

I hope this is the right place to post this because I couldn't see where else it should go.

**Comment by chamnit** [comment]
@ArtificerJon : Fourth axis is not supported by Grbl at the moment. To install this properly would be a bit of work, mainly due to the fact that Grbl assumes that the steppers are oriented in a cartesian coordinate frame. A lot of the math it does is based on this assumption. If you do install it, as some people have, it won't be optimal and performance may suffer. This is on a long list of thing I need to do. I'll be investigating it in v1.0.
