### ISSUE TITLE
Unlocked machine doesn't allow positive motion with soft limits enabled

### ISSUE THREAD

**Issue by doppelhub** [grbl/grbl#654]
Hey Sonny,
Can you explain why grbl doesn't allow positive motion when the machine is unlocked if soft limits are enabled?  Disabling soft limits allows positive motion when the machine is unlocked.  I propose grbl should ignore all machine coordinates (negative and positive) when the machine is unlocked.

Case A:
Hard limits enabled
Soft limits enabled
Homing enabled
Code:
$X
G0X-1
Expected behavior: move occurs; no errors
Actual behavior: move occurs; no errors

Case B:
Hard limits enabled
Soft limits enabled
Homing enabled
Code:
$X
G0X+1
Expected behavior: move occurs; no errors
Actual behavior: no move occurs; grbl hits soft limit

Case C:
Hard limits enabled
Soft limits disabled
Homing enabled
Code: 
$X
G0X+1
Expected behavior: move occurs; no errors
Actual behavior: move occurs; no errors

**Comment by chamnit** [comment]
Soft limits only work when homing is enabled and the machine has been homed. Otherwise the origin is set wherever the Grbl was powered up. Since Grbl expects machine coordinates to be in all negative space, you can't move in the positive direction from zero. It exceeds the soft-limits. This problem will go away once you have homed right after any power-cycle/hard reset.
