### ISSUE TITLE
Error on start-up...

### ISSUE THREAD

**Issue by Protoneer** [grbl/grbl#656]
I have occasionally had the issue where when I start-up 0.9, I get a error like this.

░░░░░░░░░░░░░error: Expected command letter

The first few characters could differ as I am using experimental Python code to interact with my boards.(Unicode conversion)

This morning I received a question for a user of my CNC boards about this. This does not happen on 0.8 by the way.

**Comment by chamnit** [comment]
This is likely caused by electrical noise during the Arduino's start up cycle and boot loader. The pins go low until it gets to the Grbl's initialization code and may turn on some things momentarily like the stepper drivers. If I'm right it should only occur during a hard reset or power-cycle, not a soft-reset.
