### ISSUE TITLE
G38.2 Probing mode in G53 machine co-ordinates

### ISSUE THREAD

**Issue by casiobearing** [grbl/grbl#934]
Currently G53 only supports G0 and G1 commands.

Is it possible to add G38.2 to G53 so that probing can use machine coordinates.

It would simplify tool changing as it would not have to modifying work coordinate systems during a tool change process. At the moment I have to use G92Z\G43.1Z.

**Comment by chamnit** [comment]
No. This is actually something I just recently looked into, because I got the same question. The LinuxCNC standard states that G53 only works with G0 and G1. So by logic, this means G38.x does not work with G53. I checked a LinuxCNC build and it comes back with a G53 with probe error. 

So I suggest that rather than using G92 or offsets, use G91 incremental mode when executing a probe. You should know where you are and how far you have to prove already. And G91 will work for that. Just makes sure you switch it back to G90 absolute mode when you are finished.
