### ISSUE TITLE
Arduino uno + Motor shield R3 + 42byghw609 stepper motor

### ISSUE THREAD

**Issue by Kingdombed** [grbl/grbl#977]
Hello everyone !

I'm working on a project and I would like to know if an arduino uno with an arduino uno motor shield R3 can run the GRBL ? I'm able to upload GRBL in the arduino but i don't know if I can find a way to configure it. I'm using a 42byghw609 stepper motor .
This is my configuration:

![img_20160427_150429](https://cloud.githubusercontent.com/assets/18011231/14853590/743e6774-0c8c-11e6-83a4-bdcaeec54a6e.jpg)

It is possible to use GRBL with this config ? What config did i need to put to make it work ?
I've made some test and i can only make the motor turn a little bit before having an error : 

![image](https://cloud.githubusercontent.com/assets/18011231/14853534/30fd41a6-0c8c-11e6-90ea-5e2b3a8074ab.png)

Thanks for your help ( sorry for my english, it's not my main language )

**Comment by electrokean** [comment]
Unfortunately you can't use that motor shield with grbl.
Although it can be used to drive a stepper motor in theory, it actually is designed to operate two brushed DC motors, and thus requires two separate direction and PWM signals - rather than the step and direction signals that grbl generates.
It also uses the completely wrong pins for the motor signals - compare the pins allocations on these two pages -
https://www.arduino.cc/en/Main/ArduinoMotorShieldR3
https://github.com/grbl/grbl/wiki/Connecting-Grbl
You need a proper stepper driver board that takes step and direction signals - like the EasyDriver or BigEasyDriver.

**Comment by electrokean** [comment]
Oh, and you appear only providing power via USB.  That wouldn't work for driving a stepper motor which will need more power (voltage & current) than USB can provide.

**Comment by Kingdombed** [comment]
Ok 
I'm have a source a voltage to power it but yeah , i can't do more with the motor shield
Thank you, Have a nice day
