### ISSUE TITLE
Change Baudrate

### ISSUE THREAD

**Issue by othtekki** [grbl/grbl#994]
Is it possible to change the baudrate of GRBL v0.9i to =<57600?
My problem is the serial wire is longer than 2m and the baudrate 115200 is for wires <2m.
I know downgrading to v0.8 is possible but i would rather keep v0.9i.

Thanks for read.

**Comment by cri-s** [comment]
Instead of
  // Set baud rate
  #if BAUD_RATE < 57600
    uint16_t UBRR0_value = ((F_CPU / (8L * BAUD_RATE)) - 1)/2 ;
    UCSR0A &= ~(1 << U2X0); // baud doubler off  - Only needed on Uno XXX
  #else
    uint16_t UBRR0_value = ((F_CPU / (4L * BAUD_RATE)) - 1)/2;
    UCSR0A |= (1 << U2X0);  // baud doubler on for high baud rates, i.e. 115200
  #endif
  UBRR0H = UBRR0_value >> 8;
  UBRR0L = UBRR0_value;

  // enable rx and tx

i use:

#define BAUD BAUD_RATE
   #include <util/setbaud.h>
UBRRH = UBRRH_VALUE;
UBRRL = UBRRL_VALUE;
   #if USE_2X
   UCSRA |= (1 << U2X);
   #else
   UCSRA &= ~(1 << U2X);
   #endif




2016-05-17 7:14 GMT, othtekki <notifications@github.com>:

**Comment by 109JB** [comment]
To answer the original question.... There is a setting in the config.h file for baud rate. You just change the value before uploading grbl to the Arduino. I don't have it in front of me right now, but the line is something like

#define baudrate 115200

**Comment by koppi** [comment]
https://github.com/grbl/grbl/blob/966abff3cc7be25f2891a8b234bc91d8eddc36a8/grbl/config.h#L36-L37
